keys:
  - &primary C9E3E6DDB69C7BB37B14F9945A71E723055533FE
  - &nixpad e047a92689ed03eb9932070722ce2adfcbedc741
  - &nixserver 84cd2d946f6b71aaa4f1609e5766e1b71b9a8f85
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - pgp:
          - *primary
          - *nixpad
          - *nixserver
